# Generated by Django 3.1.5 on 2021-12-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20211205_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
