# Generated by Django 3.1.5 on 2021-12-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211205_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='number_bids',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
