# Generated by Django 3.1.5 on 2021-12-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211205_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='highest_bid',
            new_name='highest_bid_for_listing',
        ),
    ]
